# Generated by Django 3.2.11 on 2022-01-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220125_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverinfo',
            old_name='max_passengers',
            new_name='compacity',
        ),
        migrations.RenameField(
            model_name='driverinfo',
            old_name='vehicle_Model_Make',
            new_name='vehicle_model_make',
        ),
        migrations.RemoveField(
            model_name='driverinfo',
            name='vehicle_Type',
        ),
        migrations.AddField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV')], default='COMPACT', max_length=15),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV')], default='COMPACT', max_length=15),
        ),
    ]
