# Generated by Django 3.2.11 on 2022-01-27 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20220127_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV')], default='COMPACT', max_length=15),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV')], default='COMPACT', max_length=15),
        ),
    ]
