# Generated by Django 3.2.11 on 2022-01-28 01:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220127_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinfo',
            name='sharers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('COMPACT', 'COMPACT'), ('SEDAN', 'SEDAN'), ('SUV', 'SUV')], default='COMPACT', max_length=15),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('COMPACT', 'COMPACT'), ('SEDAN', 'SEDAN'), ('SUV', 'SUV')], default='COMPACT', max_length=15),
        ),
    ]
