# Generated by Django 2.2.26 on 2022-01-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220131_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV')], default='COMPACT', max_length=15),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV')], default='COMPACT', max_length=15),
        ),
    ]
