# Generated by Django 2.2.26 on 2022-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220131_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('SEDAN', 'SEDAN')], default='COMPACT', max_length=15),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('SEDAN', 'SEDAN')], default='COMPACT', max_length=15),
        ),
    ]
