# Generated by Django 2.2.26 on 2022-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220131_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT')], default='COMPACT', max_length=15),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT')], default='COMPACT', max_length=15),
        ),
    ]
