# Generated by Django 4.0.1 on 2022-01-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220131_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('SEDAN', 'SEDAN')], default='COMPACT', max_length=15),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('SEDAN', 'SEDAN')], default='COMPACT', max_length=15),
        ),
    ]
